### ISSUE TITLE
Support Multiple Downloads

### ISSUE THREAD

**Issue by shreyasbapat** [shreyasbapat/YouTube-Downloader#18]

**Comment by shreyasbapat** [comment]
No! Support multiple downloads from the UI! 
I mean to say that the User must know the downloads happening !

**Comment by Ashwin2105** [comment]
https://github.com/Ashwin2105/YouTube-Downloader/tree/dumbidea?files=1
Here clicking download button opens a new window showing the download progress.
On downloading multiple files multiple windows open up showing the different download progress.

**Comment by shreyasbapat** [comment]
> I mean to say that the User must know the downloads happening !

**Comment by shreyasbapat** [comment]
This is not merged in the project yet

**Comment by shreyasbapat** [comment]
Closed in https://github.com/shreyasbapat/YouTube-Downloader/commit/b50cc7c8adc6650f61809e61a0a81b14ee8cc511
