### ISSUE TITLE
pytube3

### ISSUE THREAD

**Issue by hbmartin** [shreyasbapat/YouTube-Downloader#21]
Hello, opening this issue to let you know that there is a new, actively maintained, Python3 only pytube fork: https://github.com/hbmartin/pytube3

**Comment by shreyasbapat** [comment]
Good work @hbmartin . Thanks a lot for letting me know. 

Unfortunately, I don't have the bandwidth to do the porting! I will see if someone can help me do it!

**Comment by shreyasbapat** [comment]
Oh you mean, there's no API change as such! Cool, I will just change the requirements file! :)

**Comment by shreyasbapat** [comment]
Closed in https://github.com/shreyasbapat/YouTube-Downloader/commit/54cb3156ff32968ed8b936954e70d7b46f2c6988

Thanks for letting me know!
