### ISSUE TITLE
Add a button to configure proxy

### ISSUE THREAD

**Issue by shreyasbapat** [shreyasbapat/YouTube-Downloader#4]
https://app.leanboard.io/board/302fcdff-db81-407d-a730-5b6bd879a960

**Comment by Anshulgangwar63** [comment]
I would like to work if you can illustrate more want you want.

**Comment by shreyasbapat** [comment]
Suppose some user wants to download videos and he is on proxy server, we should give him the option to configure proxy. Just http and https protocols are enough!

**Comment by shreyasbapat** [comment]
Closed in #10
